#ifndef __MC_MSG_H
#define __MC_MSG_H

enum {
	MSG_SYS_CONNS	=0,
	MSG_SYS_SHUT,
	MSG_SYS_BUSY,
	MSG_SYS_BADCLS,
	MSG_SYS_NOSPACE,
	MSG_SYS_SAMECLS,
	MSG_SYS_VERSION,

	MSG_SER_OOM,
	MSG_SER_OOM_STAT,
	MSG_SER_OOM_RREQ,
	MSG_SER_OOM_WRES,
	MSG_SER_OOM_PRES,
	MSG_SER_OOM_SOBJ,
	MSG_SER_OOM_CAS,
	MSG_SER_MUL_PACK,
	MSG_SER_LAROBJ,
	MSG_SER_STYPE,
	MSG_SER_LNGOUT,

	MSG_BIN_AUTHED,
	MSG_BIN_OOM,
	MSG_BIN_NCMD,
	MSG_BIN_NFD,
	MSG_BIN_NARG,
	MSG_BIN_XKEY,
	MSG_BIN_LARG,
	MSG_BIN_NNUM,
	MSG_BIN_NSTO,
	MSG_BIN_AUTH,
	MSG_BIN_UHND,
	MSG_BIN_UKNW,

	MSG_TXT_OK,
	MSG_TXT_RESET,
	MSG_TXT_ERROR,
	MSG_TXT_STORED,
	MSG_TXT_EXISTS,
	MSG_TXT_TOUCHED,
	MSG_TXT_DELETED,
	MSG_TXT_NFOUND,
	MSG_TXT_NSTORED,
	MSG_TXT_BAD_CHUNK,
	MSG_TXT_BAD_CMDLIN,
	MSG_TXT_BAD_CMDFMT,
	MSG_TXT_BAD_CMDUSG,
	MSG_TXT_ILL_SLAB,
	MSG_TXT_ILL_TIME,
	MSG_TXT_ILL_NUM,
	MSG_TXT_USG_STAT,
	MSG_TXT_CRE_VAL,
	MSG_TXT_SLAB_DIS,

	MSG_MAX	
};

extern char* s2c_msg[MSG_MAX];
extern u8    s2c_len[MSG_MAX];

extern void msg_init(void);

#endif
